USE [master]
GO

/****** Object:  Database [u_dmatusik]    Script Date: 24.05.2023 11:40:58 ******/
CREATE DATABASE [u_dmatusik]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'u_dmatusik', FILENAME = N'/var/opt/mssql/data/u_dmatusik.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'u_dmatusik_log', FILENAME = N'/var/opt/mssql/data/u_dmatusik_log.ldf' , SIZE = 66048KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [u_dmatusik].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [u_dmatusik] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [u_dmatusik] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [u_dmatusik] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [u_dmatusik] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [u_dmatusik] SET ARITHABORT OFF 
GO

ALTER DATABASE [u_dmatusik] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [u_dmatusik] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [u_dmatusik] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [u_dmatusik] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [u_dmatusik] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [u_dmatusik] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [u_dmatusik] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [u_dmatusik] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [u_dmatusik] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [u_dmatusik] SET  ENABLE_BROKER 
GO

ALTER DATABASE [u_dmatusik] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [u_dmatusik] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [u_dmatusik] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [u_dmatusik] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [u_dmatusik] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [u_dmatusik] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [u_dmatusik] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [u_dmatusik] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [u_dmatusik] SET  MULTI_USER 
GO

ALTER DATABASE [u_dmatusik] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [u_dmatusik] SET DB_CHAINING OFF 
GO

ALTER DATABASE [u_dmatusik] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [u_dmatusik] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [u_dmatusik] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [u_dmatusik] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [u_dmatusik] SET QUERY_STORE = OFF
GO

ALTER DATABASE [u_dmatusik] SET  READ_WRITE 
GO

