USE [u_dmatusik]
GO

/****** Object:  Table [dbo].[Miasto]    Script Date: 22.07.2023 13:44:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Miasto](
	[ID_miasta] [int] NOT NULL,
	[Nazwa_miasta] [nchar](30) NOT NULL,
	[Kod_pocztowy] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Miasto] PRIMARY KEY CLUSTERED 
(
	[ID_miasta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [uc_Kod_pocztowy] UNIQUE NONCLUSTERED 
(
	[Kod_pocztowy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [unique_kod_pocztowy] UNIQUE NONCLUSTERED 
(
	[Kod_pocztowy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

