USE [u_dmatusik]
GO

/****** Object:  Table [dbo].[Sprzedawcy]    Script Date: 22.07.2023 13:44:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sprzedawcy](
	[id_sprzedawcy] [int] NOT NULL,
	[nazwa_sprzedawcy] [nchar](30) NOT NULL,
 CONSTRAINT [PK_Sprzedawcy] PRIMARY KEY CLUSTERED 
(
	[id_sprzedawcy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Sprzedawcy_nazwa_sprzedawcy] UNIQUE NONCLUSTERED 
(
	[nazwa_sprzedawcy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

